### ISSUE TITLE
Issue with members property

### ISSUE THREAD

**Issue by surendraatgithub** [Rambatino/CHAID#107]
Issue with members property i.e. 
node_obj = CHAID.Node()
print(node_obj) or node_obj.__repr__() fails because members property expects dep_v to be not none.
If dep_v is mandatory then default value should be removed  in __init__.

**Comment by Rambatino** [comment]
Not sure I follow. 

Are you able to leave a reproducible example.

Thanks!

**Comment by surendraatgithub** [comment]
Sure will do

**Comment by Rambatino** [comment]
@surendraatgithub I'm going to close this due to inactivity. 

If you're able to get a reproducible example, please feel free to open a new Issue with that.
