### ISSUE TITLE
Error while importing in Jupyter Notebook

### ISSUE THREAD

**Issue by 1DanielG** [Rambatino/CHAID#108]
I have installed last version of CHAID Package, when I am trying to import CHAID into my notebook .  getting a syntax error 

`from CHAID import Tree`

error message:

```
 File "C:\...\Local\Continuum\anaconda3\lib\site-packages\CHAID\graph.py", line 75
    file = 'C:\...\Documents\Python Scripts\CHAID\temp\' + ("%.20f" % time.time()).replace('.', '') + '.png'


    ^
SyntaxError: invalid syntax
```

**Comment by Rambatino** [comment]
Hi @1DanielG I've made a note to look into this in the next few hours.

**Comment by Rambatino** [comment]
Ahh I can see the error (line 75 of `graph.py`)

# Current Version

https://github.com/Rambatino/CHAID/blob/master/CHAID/graph.py#L75

# Old Version

https://github.com/Rambatino/CHAID/blob/f196f45a627bfd38610dbd8aa2c55edc9390aa0d/CHAID/graph.py#L75


You'll see in the most recent version that it doesn't use that method anymore. Thus your CHAID library isn't up to date.

You're most likely on version ~5.2.0, you'll need 5.3.0.

**Comment by Rambatino** [comment]
What is your output of `pip freeze | findstr CHAID`?

**Comment by 1DanielG** [comment]
Yes! I had 5.2.1 . I upgraded it to 5.3.0. It works fine now . Thanks man

**Comment by Rambatino** [comment]
Amazing 🙌
