### ISSUE TITLE
Documentation for library

### ISSUE THREAD

**Issue by divatemangesh** [Rambatino/CHAID#118]
Hello  team

Can somebody create documentation for the library. So that  some one can understand it easily.  May be on read the docs

**Comment by Rambatino** [comment]
Hi @divatemangesh the README.md has a lot in it. 

What is is that you're trying to do?

**Comment by divatemangesh** [comment]
I wanted some method by  using which I can  grow the tree. level by level based on choice. 
And choice can be one of following

- find next best split for specific node
- choose Column one which I want to split data


Let's say as in titanic data  I am  getting "Sex" as  first split and "pClass" a
 second split. On. For both male and female node 

but if suppose I want to split male node on  "Cabin" variable and  female on "pClass"

How to do that ? 
is that something one of the feature of this library or going to be one?

**Comment by Rambatino** [comment]
We don't currently support that functionality, unfortunately.
It also won't be built any time soon, but you're welcome to create a PR with that functionality.
