### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by ondratybl** [Rambatino/CHAID#128]
how do I predict using this class for data which have not been used for training? I see only model_predictions which only retrieves predictions for the training data... thanks a lot :)

**Comment by Rambatino** [comment]
Hi @ondratybl, you would like to apply the model to see its f1 score on unseen data, for instance?

That's kinda ML based, and I haven't actually got around to implementing such a thing. I'm not sure how difficult it would be, like it would just be how well that model runs on new data and look at what predictions match and what don't.

If you want to submit a PR please feel free to do so.

**Comment by Rambatino** [comment]
I think this may be what you're after: https://github.com/Rambatino/CHAID/pull/91

**Comment by ondratybl** [comment]
@Rambatino thanks a lot. It seems to be what I need. tree.predict() has been removed for some reason in the current version?
