### ISSUE TITLE
Error while running tree.render()

### ISSUE THREAD

**Issue by macmagic34** [Rambatino/CHAID#131]
I don't know but for some reason running

tree.render(path='some_path', view=False)

Gives me the below:-

"Image export using the kaleido engine requires the kaleido package, which can be installed using pip install kaleido"

I've installed it already and still getting the same error. Any help?

**Comment by tomascortes** [comment]
i got that error because i didn't had installed graphviz and orca

**Comment by Rambatino** [comment]
Thanks @tomascortes
