### ISSUE TITLE
np.float is deprecated

### ISSUE THREAD

**Issue by kenny-devarapalli** [Rambatino/CHAID#133]
**AttributeError**: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.

**Location of Error**
File ~/.local/lib/python3.8/site-packages/CHAID/column.py:131, in NominalColumn.substitute_values(self, vect)
    129     np.place(arr, arr==value, new_id)
    130     self.metadata[new_id] = value
--> 131 arr = arr.astype(np.float)

**Comment by Rambatino** [comment]
This has been fixed and will be released in the new version
