### ISSUE TITLE
any working example?

### ISSUE THREAD

**Issue by sriramab** [Rambatino/CHAID#64]
Hi, 

I am interested in using your package for my research. Do you have any working tutorial document on how to use it on a dataset?

thank you

**Comment by Rambatino** [comment]
Hi @sriramab, does the README.md not satisfy your requirements?

If not, do let us know if you have any specific questions regarding the API of this project.

**Comment by sriramab** [comment]
Hi, 

I installed via pip, but my python does not recognise the import statement. I may have forgotten to read, is this for python 2x or 3x? I am using 3x of anaconda with IDE pycharm community edition. pip install is a success and repeating the process clearly shows that CHAID is already installed. 

I am unable to get this working.

**Comment by Rambatino** [comment]
It works for all python.

Can you post the commands that you are using?

**Comment by sriramab** [comment]
Hi,

When I installed (pip)  via mac terminal , the packages were installed but were not detected by pycharm. Then installed the packages via package manager in pycharm, then it works. Would you know why? 

I am a beginner in python and I plan to use your package to generate decision trees for my model. 

Thank you.

**Comment by Rambatino** [comment]
I'm not sure how pycharm works, having never used it. This is a pycharm issue, and it will be to do with where pycharm looks for your packages, you'll have to raise an issue with them.

Have you tried: https://stackoverflow.com/questions/19885821/how-do-i-import-modules-in-pycharm

**Comment by sriramab** [comment]
Thank you .
