### ISSUE TITLE
Creating tree different from README

### ISSUE THREAD

**Issue by asram6** [Rambatino/CHAID#65]
Hi,

I am running the example for creating a CHAID tree in the README. When I get to the line tree.print_tree(), I get: ([], {1: 5, 2: 5}, <Invalid Chaid Split>). 
This is different from the result in the README, so I was confused why this is happening. 
Also, could you give an overview of what the attributes are in the Tree object so I can better understand the output?

Thanks!

**Comment by sriramab** [comment]
Yes, I also have different result.

**Comment by Rambatino** [comment]
Hi, let me review the README and get back to you. thanks!

**Comment by Rambatino** [comment]
Okay, so between v3.0.0 -> v.4.0.0 we changed the default for `min_child_node_size`. It was set at 0, but then we made it in line with `min_parent_node_size`, and thus changed it to 30. 

I've updated the README, thanks!

**Comment by Rambatino** [comment]
Will have a think about a way to write up the different classes of the Tree, so they can be better understood. May have a look this weekend.

**Comment by asram6** [comment]
Ok, thank you. For now, could you explain what this snippet means so that I at least have some idea right now:
`([], {1: 5, 2: 5}, ('a', p=0.001565402258, score=10.0, groups=[[1], [2]]), dof=1))`
