### ISSUE TITLE
Why isn't there a predict function ?

### ISSUE THREAD

**Issue by vsharathchandra** [Rambatino/CHAID#72]
I split the data into train and test data.I have run the chaid on train data,Now I would like to use it to predict the output of test data.I want to do this for classification.

**Comment by Rambatino** [comment]
Hmm I do remember doing something with this, but at the moment it doesn't appear to be in the main library.

I'll have a look at the work I did a while ago, but it won't be production ready any time soon.

You're of course welcome to build it out yourself

**Comment by Rambatino** [comment]
@coderking7 are you able to have a try with :point_up:

**Comment by Rambatino** [comment]
@coderking7 please test on that branch with:
``` python
python -m CHAID tests/data/titanic.csv survived sex embarked --max-depth 77 --min-parent-node-size 1 --alpha-merge 0.6 --min-child-node-size 10 --accuracy
```

**Comment by jm2909** [comment]
I have tried a basic implementation of the predict function for my own project. 
This is the link of the code: 
**https://github.com/jm2909/CHAID-Predict-Function-Testing.git**

I am a new guy in python. Any suggestions or critics will be appreciated, if there is any implementation mistake.

**Comment by Rambatino** [comment]
@jm2909 I unfortunately don't have too much time to go and read so much code! However, if it does what you need then great! 👍 

Feel free to for CHAID and contribute if it works and has a sufficiently acceptable API.

I'm going to close this due to inactivity now.

**Comment by VivianMagri** [comment]
I have recently started working with analytics and I came here looking for a model to do the same as vsharathchandra described and. When I couldn't find on documentation anything of the sort of a method 'predict', I came to the issues and discovered it really wasn't thought for this goal.
Pardon my ignorance, but now I really am confused. What was the intended use of this library? I had the idea that the purpose of a decision tree (or supervised machine learning models in general) where always making prediction on unseen data.

**Comment by VivianMagri** [comment]
I have recently started working with analytics and I came here looking for a model to do the same as vsharathchandra described. When I couldn't find on documentation anything of the sort of a method 'predict', I came to the issues and discovered it really wasn't thought for this goal.
Pardon my ignorance, but now I really am confused. What was the intended use of this library? I had the idea that the purpose of a decision tree (or supervised machine learning models in general) where always making prediction on unseen data.

**Comment by Rambatino** [comment]
The intended use of this library is to run it on a set of data and it will tell you what independent variables have a large affect on an outcome variable. E.g. Males under 40 really like drinking or whatever. It originally wasn't intended to make predictions on unseen data - it's more classical statistics [apply model to data].

Have a look at XGBoost Classifier and Regressor if that's the functionality you want - it will give more accurate predictions than CHAID will
