### ISSUE TITLE
Maybe an error in the doc?

### ISSUE THREAD

**Issue by pietrogiuffrida** [Rambatino/CHAID#79]
Hi Rambatino,
thanks for your work.
Maybe this code:
`tree = Tree.from_pandas_df(df, dict(zip(independent_variable_columns, 'nominal' * 3)), dep_variable)`
should be:
`tree = Tree.from_pandas_df(df, dict(zip(independent_variable_columns, ['nominal'] * 3)), dep_variable)`
Regards

**Comment by shaheming** [comment]
Yes, I think there is some problem too!

**Comment by Rambatino** [comment]
Yep you're right. Will fix now. If you find anything else, do let me know!
