### ISSUE TITLE
IS ID5 tree equalst to CHAID in concepts?

### ISSUE THREAD

**Issue by appleyuchi** [Rambatino/CHAID#92]
Is ID5 tree equivalent to CHAID in concepts?
Many thanks

**Comment by Rambatino** [comment]
Most probably not, as ID5 was not taken into consideration when building the algorithm.

**Comment by Rambatino** [comment]
If you could explain your question with specifics related to tree building properties I can answer in more detail

**Comment by Rambatino** [comment]
Closing as stale.
