### ISSUE TITLE
how to graphically display the tree?

### ISSUE THREAD

**Issue by greghor** [Rambatino/CHAID#93]

**Comment by greghor** [comment]
Is there any tool available to visualize the chaid tree? Maybe something equivalent to export_graphiz for CART?

**Comment by Rambatino** [comment]
There is this: https://github.com/Rambatino/CHAID/blob/master/CHAID/tree.py#L198
![image](https://user-images.githubusercontent.com/3631109/55133245-eb350280-5189-11e9-94fc-414eb3f258f7.png)

Which uses https://github.com/Rambatino/CHAID/blob/master/CHAID/tree.py#L2 

If you look at the treelib source code there is this: https://github.com/caesar0301/treelib/blob/master/treelib/tree.py#L865

![image](https://user-images.githubusercontent.com/3631109/55133404-73b3a300-518a-11e9-863e-0111e097580a.png)


Which I think is what you want. So you should be able to do:

``` python
tree.to_tree(). to_graphviz(filename="") # untested
```

**Comment by greghor** [comment]
Thanks for your reply! I ll take a look at it!

**Comment by Rambatino** [comment]
@greghor have a look at https://github.com/Rambatino/CHAID/pull/94
